FROM python:3.12-slim

RUN pip install --no-cache-dir mlflow psycopg2-binary

WORKDIR /mlflow

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}", \
     "--default-artifact-root", "./artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]
     