name: Machine Learning Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: churn_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run ML Pipeline
        env:
          PYTHONPATH: .
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: churn_db
          DB_HOST: localhost
          DB_PORT: 5432
          RAW_DATA_TRAINING_PATH: tests/fixtures/sample_training.csv
          RAW_DATA_TESTING_PATH: tests/fixtures/sample_testing.csv
        run: |
          uv run pipelines/01_data_ingestion.py
          uv run pytest tests/test_data_quality.py